// =============================================================================
// ARGIA TESTS -- tests_regression/v2/CulliganBaselineV2Tests.gs
// -----------------------------------------------------------------------------
// v2 regression baseline -- locks the headline numbers from a real CULLIGAN
// engine run against every v2 output sheet shipped by chunks 1..7.
//
// PURPOSE
//   The legacy baseline (tests_regression/baseline/CulliganBaselineTests.gs)
//   locks values on the legacy MDC / BOM / INSTALLATION / PROJECT_CARD sheets.
//   This test mirrors that pattern for the v2 sheets so the cutover PR
//   (plan Chunk 11) can delete the legacy file and rename this one without
//   losing assertion coverage.
//
// SCOPE (read-only, same as legacy)
//   Asserts on whatever is currently in the v2 sheets. Caller is responsible
//   for:
//     1. Running runArgiaEngine() against CULLIGAN inputs (writes MDC_v2,
//        BOM_v2, INSTALLATION_v2, PROJECT_CARD_v2, CFE_OUTPUT_v2).
//     2. Running "Generate RFQs v2" from the ARGIA menu (writes the six
//        RFQ_*_v2 sheets).
//   If the workbook holds a different project or RFQs are stale, the
//   identity asserts at the start of each block will catch it and the block
//   will short-circuit with a readable failure.
//
// LOCK SOURCE
//   Workbook ARGIA_ENGINE__39_.xlsx, _META.calculated_at = 2026-05-26T18:53Z,
//   engine v3.5.0, DB 2026.05. Real CULLIGAN inputs (1350 panels, 5 inverters,
//   864 kWdc, 700 kWac, PPA_ROOF business case, MONTERREY, BESS enabled with
//   9 x HW_LUNA_241_2S1 stacks, PEAK_SHAVING strategy, DC_COUPLED).
//
//   Lock values were read directly from the v2 sheets of this workbook, not
//   copied from the legacy baseline. Several v2 totals differ from legacy
//   locks because (a) BESS line items now flow through BOM/PC/INSTALLATION
//   and (b) the legacy baseline drifted from engine v2.3.5 to v3.5.0 without
//   being re-locked.
//
// RE-LOCK 2026-06-09 (engine v4.12.1, DB 2026.05) -- via Run CULLIGAN E2E.
//   32 locks updated from the v4.0.0 values. Every change traced to a known,
//   correct engine improvement (verified, not a regression):
//     - DC vdrop 1.36%->0.75%, DC cable 12600->6111 m, DC cost 58.4k->49.6k:
//       DC-length-basis fix (same fix that took PROLOGIS 3.66%->1.18%).
//     - MDC array area 3564->4376 m2: grossArea now = panelArea x qty x
//       walkwayFactor (real footprint, not net glass).
//     - AC cost 78.3k->142.7k, breaker 1250->1200 A: AC ampacity 125%-rule fix
//       + 500-1000 kcmil rows -> correctly-sized 3x600 kcmil feeder (old feeder
//       was the UNSAFE undersized one we fixed).
//     - BESS +/-0.1%, Install +/-1-2%: calc/labor refinements.
//     - CFE annuals -3 to -5%: the v4.0.0 BESS dispatch rewrite + 2026.05
//       tariff DB (Block E header already flagged these would move).
//     - Project Card / grand totals: pure downstream arithmetic of the above.
//   RFQ Block F: INFO-skips (RFQ sheets not generated by the E2E yet).
//
// SUPERSEDES
//   The MDC_v2-only version of this file (pre-cutover-prep). All blocks
//   previously "not yet covered" are now covered: BOM_v2, INSTALLATION_v2,
//   PROJECT_CARD_v2, CFE_OUTPUT_v2, RFQ_*_v2.
//
// CUTOVER NOTES (for Chunk 11 PR)
//   - The PARITY blocks (Block 5 in each sheet section) compare v2 against
//     the legacy sheet. After cutover the legacy sheets are gone and these
//     blocks become noise -- DELETE them in the cutover PR. They're called
//     out inline with a "REMOVE AT CUTOVER" comment so the diff is easy.
//   - At cutover the v2 sheet names lose the "_v2" suffix. Search-and-
//     replace MDC_v2 -> MDC etc. and rename this file to
//     tests_regression/baseline/CulliganBaselineTests.gs, replacing the
//     legacy one in the same commit.
//   - The engine version assert was relocked to "4.0.0" (2026-05-28) with
//     the strategy-aware dispatch MAJOR release. The pinned numbers are
//     material/spec + PV/structural only, which the dispatch change does
//     not affect, so they carried forward unchanged.
//
// TAGS
//   'chunk1' kept for backward compat with the per-chunk runner.
//   'cutover-ready' makes this discoverable in the Chunk 11 prep.
// =============================================================================


registerTest({
  id      : 'REG_CULLIGAN_BASELINE_V2',
  group   : 'regression',
  module  : 'regression/v2/culligan',
  scenarios: [],
  tags    : ['regression', 'baseline', 'culligan', 'v2',
             'read-only', 'chunk1', 'cutover-ready'],
  source  : 'tests_regression/v2/CulliganBaselineV2Tests.gs',
  fn: function (t, ctx) {
    t.suite('REG regression/v2/culligan: CULLIGAN reference numbers (all v2 sheets)');

    var ss = ctx.ss;
    if (!ss) { t.info('skipped', 'no spreadsheet context'); return; }

    t.info('caveat',
      'Read-only test. Before running:\n' +
      '  1. Run "Generate MDC and BOM" against CULLIGAN inputs (engine pass).\n' +
      '  2. Run "Generate RFQs v2" from the ARGIA menu.\n' +
      'The first identity assertion in each block confirms the workbook ' +
      'holds CULLIGAN and short-circuits the block on mismatch so failures ' +
      'are interpretable.');

    // Tolerances -- same scheme as legacy baseline, plus a few new ones.
    var TOL_RATIO = 0.001;   // dimensionless 3-decimal lock
    var TOL_CUR   = 0.05;    // amps, 2-decimal lock
    var TOL_PCT   = 0.0005;  // voltage drops, 4-decimal lock
    var TOL_USD   = 1.0;     // BOM / PC totals to nearest USD
    var TOL_MXN   = 50.0;    // MXN locks to nearest 50 pesos (FX rounding)
    var TOL_MXN_BIG = 1000.0; // annual CFE bills are ~$10M MXN, scale tolerance
    var TOL_KWH   = 100.0;   // annual kWh in the millions, ±100 is tight

    // ====================================================================
    // BLOCK A: MDC_v2 -- engineering decisions
    // ====================================================================
    t.suite('A. MDC_v2 -- engineering decisions');

    if (!ss.getSheetByName('MDC_v2')) {
      t.fail('required sheet missing',
             'MDC_v2 -- created by setupMdcTemplate() during Step 10-v2. ' +
             'If the engine ran but the sheet is missing, the v2 try/catch ' +
             'swallowed an error -- check the engine log.');
      return;
    }
    var mdc = ss.getSheetByName('MDC_v2');

    // -- A1: identity (must match before any number is meaningful) --
    var mdcProj = String(mdc.getRange('C7').getValue() || '').trim();
    if (mdcProj !== 'CULLIGAN') {
      // [4.16.2] INFO, not FAIL. A workbook holding a different project (e.g. a
      // real PROLOGIS deal) is a "can't run this CULLIGAN test here" condition
      // -- a SKIP -- not an engine defect. Reporting it as FAIL caused
      // repeated false alarms on every test run against a live customer
      // workbook. The CULLIGAN E2E loads CULLIGAN first, so inside the E2E
      // this branch is not taken and the real assertions below run.
      t.info('CULLIGAN baseline skipped (workbook holds a different project)',
             'MDC_v2.C7 = "' + mdcProj + '" (expected "CULLIGAN"). This is the '
             + 'intended guard, NOT a failure. To run the CULLIGAN baseline: '
             + 'Administrator Panel > Test > Run CULLIGAN E2E (loads CULLIGAN, '
             + 'generates, asserts, restores your inputs). All blocks skipped.');
      return;
    }
    t.assert('MDC_v2.C7 project name', 'CULLIGAN', mdcProj);
    t.assert('MDC_v2.C8 client name',  'CULLIGAN TEST',
             String(mdc.getRange('C8').getValue() || '').trim());

    // -- A2: scale --
    t.assert('MDC_v2.C11 module count',   1350, mdc.getRange('C11').getValue());
    t.assert('MDC_v2.C12 inverter count',    5, mdc.getRange('C12').getValue());

    // -- A3: DC sizing --
    t.assertNear('MDC_v2.C17 DC/AC ratio',
                 1.234, mdc.getRange('C17').getValue(), TOL_RATIO);
    t.assertNear('MDC_v2.C22 design current (A)',
                 24.05, mdc.getRange('C22').getValue(), TOL_CUR);  // A2b: Isc,corr (FR-205-03), was 23.64 on STC Isc (+1.73% @ ~60C); conductor unchanged
    t.assertContains('MDC_v2.C26 DC conductor includes 10 AWG',
                     String(mdc.getRange('C26').getValue()), '10 AWG');
    t.assertContains('MDC_v2.C28 DC OCPD includes 25',
                     String(mdc.getRange('C28').getValue()), '25');
    t.assertNear('MDC_v2.C30 DC voltage drop pct',
                 0.0075, mdc.getRange('C30').getValue(), TOL_PCT);

    var vocColdRaw = String(mdc.getRange('C35').getValue() || '');
    var vmpHotRaw  = String(mdc.getRange('C36').getValue() || '');
    t.assertContains('MDC_v2.C35 Voc cold = 1031.9 V', vocColdRaw, '1031.9');
    t.assertContains('MDC_v2.C36 Vmp hot = 752.8 V',   vmpHotRaw,  '752.8');

    // -- A4: AC sizing --
    var acMainRaw  = String(mdc.getRange('C56').getValue() || '');
    var breakerRaw = String(mdc.getRange('C57').getValue() || '');
    var transRaw   = String(mdc.getRange('C66').getValue() || '');
    t.assertContains('MDC_v2.C56 AC main current = 842 A', acMainRaw,  '842');
    t.assertContains('MDC_v2.C57 main breaker = 1200 A',   breakerRaw, '1200');
    t.assertContains('MDC_v2.C66 transformer = 1000 kVA',  transRaw,   '1000');

    // -- A5: emission status & layout --
    t.assert('MDC_v2.C72 emission status',
             'EMITTABLE WITH OBSERVATIONS',
             String(mdc.getRange('C72').getValue() || '').trim());
    t.assertContains('MDC_v2.C88 array area = 4376 m2',
                     String(mdc.getRange('C88').getValue() || ''), '4376');
    t.assertContains('MDC_v2.C91 DC cable total = 6111 m',
                     String(mdc.getRange('C91').getValue() || ''), '6111');

    // -- A6: BESS section (§7) -- new in v2, never covered by legacy baseline --
    t.assertContains('MDC_v2.B100 BESS section header',
                     String(mdc.getRange('B100').getValue() || ''),
                     'ALMACENAMIENTO');
    t.assertContains('MDC_v2.C101 BESS product / strategy = HW_LUNA + PEAK_SHAVING',
                     String(mdc.getRange('C101').getValue() || ''),
                     'HW_LUNA_241_2S1');
    t.assertContains('MDC_v2.C101 BESS strategy = PEAK_SHAVING',
                     String(mdc.getRange('C101').getValue() || ''),
                     'PEAK_SHAVING');
    t.assertContains('MDC_v2.C102 BESS nominal capacity = 2169 kWh',
                     String(mdc.getRange('C102').getValue() || ''), '2169');
    t.assertContains('MDC_v2.C103 BESS nominal power = 972 kW',
                     String(mdc.getRange('C103').getValue() || ''), '972');
    t.assertContains('MDC_v2.C105 BESS topology = DC_COUPLED',
                     String(mdc.getRange('C105').getValue() || ''),
                     'DC_COUPLED');
    // T5 (per-stack BESS model): the 9 × 108 kW stacks are now sized as 9
    // separate home-runs of ~156 A each (not one impossible 1406 A run). The
    // BESS run-1 OCPD is therefore the per-stack 175 A breaker, which correctly
    // protects the per-stack 2/0 conductor (NEC 240.4 — no warning). T1 bumped
    // the per-stack conductor 1/0 -> 2/0 (156 A exceeds 1/0's 150 A at 75 C),
    // so C107 now reads "9 × Cond 2/0 / OCPD 175 A / EGC <n>". OCPD is unchanged.
    t.assertContains('MDC_v2.C107 BESS circuit run-1 sized (per-stack)',
                     String(mdc.getRange('C107').getValue() || ''),
                     'OCPD 175');

    // -- A7: PARITY vs legacy MDC -- REMOVE AT CUTOVER (Chunk 11) --
    var legacyMdc = ss.getSheetByName('MDC');
    if (legacyMdc) {
      var checkMdcParity = function (cell, label) {
        var v2  = mdc.getRange(cell).getValue();
        var leg = legacyMdc.getRange(cell).getValue();
        var v2s  = String(v2  === null ? '' : v2);
        var legs = String(leg === null ? '' : leg);
        t.assert('PARITY MDC.' + cell + ' (' + label + ')', legs, v2s);
      };
      checkMdcParity('C7',  'project');
      checkMdcParity('C8',  'client');
      checkMdcParity('C11', 'module count');
      checkMdcParity('C12', 'inverter count');
      checkMdcParity('C26', 'DC conductor');
      checkMdcParity('C57', 'main breaker');
      checkMdcParity('C66', 'transformer');
      checkMdcParity('C72', 'emission status');
    } else {
      t.info('MDC parity skipped', 'legacy MDC sheet not present');
    }

    // ====================================================================
    // BLOCK B: BOM_v2 -- material costs (PV + BESS combined)
    // ====================================================================
    t.suite('B. BOM_v2 -- material costs incl. BESS');

    if (!ss.getSheetByName('BOM_v2')) {
      t.fail('required sheet missing', 'BOM_v2');
    } else {
      var bom = ss.getSheetByName('BOM_v2');

      // -- B1: identity (banner cell carries project name) --
      var bomTitle = String(bom.getRange('A4').getValue() || '');
      t.assertContains('BOM_v2.A4 banner carries CULLIGAN', bomTitle, 'CULLIGAN');
      t.assertContains('BOM_v2.A4 banner carries 1350 mod', bomTitle, '1350');
      t.assertContains('BOM_v2.A4 banner carries 864.00 kWp', bomTitle, '864.00 kWp');

      // -- B2: section subtotals (col F = USD) --
      t.assertNear('BOM_v2.F13 SUBTOTAL panels USD',
                   128736.00,  bom.getRange('F13').getValue(), TOL_USD);
      t.assertNear('BOM_v2.F20 SUBTOTAL inverters USD',
                   31200.00,   bom.getRange('F20').getValue(), TOL_USD);
      t.assertNear('BOM_v2.F25 SUBTOTAL structure USD',
                   24300.00,   bom.getRange('F25').getValue(), TOL_USD);
      t.assertNear('BOM_v2.F35 SUBTOTAL DC USD',
                   49604.49,   bom.getRange('F35').getValue(), TOL_USD);
      t.assertNear('BOM_v2.F63 SUBTOTAL AC USD',
                   144036.70,  bom.getRange('F63').getValue(), TOL_USD);
      t.assertNear('BOM_v2.F68 SUBTOTAL transformer USD',
                   0.00,       bom.getRange('F68').getValue(), TOL_USD);
      t.assertNear('BOM_v2.F78 SUBTOTAL monitoring+permits USD',
                   6724.32,    bom.getRange('F78').getValue(), TOL_USD);

      // -- B3: BESS section subtotal (§8, new in v2) --
      t.assertContains('BOM_v2.B79 BESS section header',
                       String(bom.getRange('B79').getValue() || ''),
                       'ALMACEN');
      t.assertNear('BOM_v2.F92 SUBTOTAL BESS USD',
                   1602797.97, bom.getRange('F92').getValue(), TOL_USD);
      t.assertNear('BOM_v2.G92 SUBTOTAL BESS MXN',
                   29651762.36, bom.getRange('G92').getValue(), TOL_MXN);

      // -- B4: grand total (row 94 in v2 because BESS section pushed it down) --
      t.assertNear('BOM_v2.F94 GRAND TOTAL USD',
                   1987399.478, bom.getRange('F94').getValue(), TOL_USD);
      t.assertNear('BOM_v2.G94 GRAND TOTAL MXN',
                   36766890.34, bom.getRange('G94').getValue(), TOL_MXN);

      // -- B5: PARITY vs legacy BOM -- REMOVE AT CUTOVER (Chunk 11) --
      // Section subtotals only -- grand totals are on different rows because
      // v2 has a BESS section that legacy doesn't.
      var legacyBom = ss.getSheetByName('BOM');
      if (legacyBom) {
        var checkBomParity = function (cell, label) {
          var v2  = bom.getRange(cell).getValue();
          var leg = legacyBom.getRange(cell).getValue();
          if (typeof v2 === 'number' && typeof leg === 'number') {
            t.assertNear('PARITY BOM.' + cell + ' (' + label + ')',
                         leg, v2, TOL_USD);
          } else {
            t.assert('PARITY BOM.' + cell + ' (' + label + ')',
                     String(leg == null ? '' : leg),
                     String(v2 == null ? '' : v2));
          }
        };
        checkBomParity('F13', 'panels subtotal');
        checkBomParity('F20', 'inverters subtotal');
        checkBomParity('F25', 'structure subtotal');
        checkBomParity('F35', 'DC subtotal');
        checkBomParity('F63', 'AC subtotal');
        checkBomParity('F78', 'monitoring subtotal');
      } else {
        t.info('BOM parity skipped', 'legacy BOM sheet not present');
      }
    }

    // ====================================================================
    // BLOCK C: INSTALLATION_v2 -- labor / equipment costs
    // ====================================================================
    t.suite('C. INSTALLATION_v2 -- labor / equipment');

    if (!ss.getSheetByName('INSTALLATION_v2')) {
      t.fail('required sheet missing', 'INSTALLATION_v2');
    } else {
      var inst = ss.getSheetByName('INSTALLATION_v2');

      // -- C1: scale (must agree with MDC) --
      t.assertNear('INSTALL_v2.B6 DC kWp',     864, inst.getRange('B6').getValue(), 0.5);
      t.assertNear('INSTALL_v2.B7 AC kW',      700, inst.getRange('B7').getValue(), 0.5);
      t.assert('INSTALL_v2.B8 module count', 1350, inst.getRange('B8').getValue());
      t.assert('INSTALL_v2.B9 inverter count',  5, inst.getRange('B9').getValue());

      // -- C2: totals (G column = MXN) --
      // [T5 per-stack BESS] REFRESHED: 9 stack home-runs add termination + pull
      // labor and equipment. LABOR 161,259.90->169,528.76, EQUIP 166,880->171,060,
      // OTHER 488,460.56->498,906.47, GRAND 816,600.46->839,495.23,
      // MXN/kWp 945.14->972, CAPEX D40 +430,305.12.
      t.assertNear('INSTALL_v2.G5 TOTAL LABOR MXN',
                   169528.76, inst.getRange('G5').getValue(), TOL_MXN);
      t.assertNear('INSTALL_v2.G6 TOTAL EQUIP MXN',
                   171060.00, inst.getRange('G6').getValue(), TOL_MXN);
      t.assertNear('INSTALL_v2.G7 TOTAL OTHER MXN',
                   498906.47, inst.getRange('G7').getValue(), TOL_MXN);
      t.assertNear('INSTALL_v2.G9 GRAND TOTAL MXN',
                   839495.23, inst.getRange('G9').getValue(), TOL_MXN);
      t.assertNear('INSTALL_v2.G10 MXN per kWp',
                   972.0,     inst.getRange('G10').getValue(), 1.0);

      // -- C3: PARITY vs legacy INSTALLATION -- REMOVE AT CUTOVER (Chunk 11) --
      var legacyInst = ss.getSheetByName('INSTALLATION');
      if (legacyInst) {
        var checkInstParity = function (cell, label) {
          var v2  = inst.getRange(cell).getValue();
          var leg = legacyInst.getRange(cell).getValue();
          t.assertNear('PARITY INSTALL.' + cell + ' (' + label + ')',
                       leg, v2, TOL_MXN);
        };
        checkInstParity('G5',  'labor total');
        checkInstParity('G6',  'equip total');
        checkInstParity('G7',  'other total');
        checkInstParity('G9',  'grand total');
        checkInstParity('G10', 'MXN per kWp');
      } else {
        t.info('INSTALLATION parity skipped', 'legacy INSTALLATION sheet not present');
      }
    }

    // ====================================================================
    // BLOCK D: PROJECT_CARD_v2 -- the salesperson deliverable
    // ====================================================================
    // PC_v2 uses a different row layout from legacy PC -- the cell map below
    // matches the PC_V2_ROW constants in 00_Main.js (rows 19, 39, 40, etc.)
    // NOT the legacy PC cell map. This is intentional, not a bug.
    // ====================================================================
    t.suite('D. PROJECT_CARD_v2 -- sales deliverable');

    if (!ss.getSheetByName('PROJECT_CARD_v2')) {
      t.fail('required sheet missing', 'PROJECT_CARD_v2');
    } else {
      var pc = ss.getSheetByName('PROJECT_CARD_v2');

      // -- D1: identity --
      t.assert('PC_v2.C4 customer', 'CULLIGAN TEST',
               String(pc.getRange('C4').getValue() || '').trim());
      t.assert('PC_v2.C5 project',  'CULLIGAN',
               String(pc.getRange('C5').getValue() || '').trim());

      // -- D2: cost breakdown col C = USD, col D = MXN (rows 31-39) --
      t.assertNear('PC_v2.C31 panels USD',
                   128736.0,  pc.getRange('C31').getValue(), TOL_USD);
      t.assertNear('PC_v2.C32 inverters USD',
                   31200.0,   pc.getRange('C32').getValue(), TOL_USD);
      t.assertNear('PC_v2.C33 structure USD',
                   24300.0,   pc.getRange('C33').getValue(), TOL_USD);
      t.assertNear('PC_v2.C34 DC USD',
                   49604.0,   pc.getRange('C34').getValue(), TOL_USD);
      t.assertNear('PC_v2.C35 AC USD',
                   144037.0,  pc.getRange('C35').getValue(), TOL_USD);
      t.assertNear('PC_v2.C36 monitoring USD',
                   724.0,     pc.getRange('C36').getValue(), TOL_USD);
      t.assertNear('PC_v2.C37 permits USD',
                   6000.0,    pc.getRange('C37').getValue(), TOL_USD);
      t.assertNear('PC_v2.C38 installation USD',
                   45378.0,   pc.getRange('C38').getValue(), TOL_USD);
      t.assertNear('PC_v2.C39 BESS USD',
                   1602798.0, pc.getRange('C39').getValue(), TOL_USD);

      // -- D3: TOTAL (row 40) --
      t.assertNear('PC_v2.C40 TOTAL cost USD',
                   2032778.0, pc.getRange('C40').getValue(), TOL_USD);
      t.assertNear('PC_v2.D40 TOTAL cost MXN',
                   37606386.0, pc.getRange('D40').getValue(), TOL_MXN);

      // -- D4: sell side -- USD/Wp string and gross profit --
      var sellRaw = String(pc.getRange('H17').getValue() || '');
      t.assertContains('PC_v2.H17 sell USD/Wp = 2.768',
                       sellRaw, '2.768');
      t.assertNear('PC_v2.H40 sell total USD',
                   2391503.0, pc.getRange('H40').getValue(), TOL_USD);
      t.assertNear('PC_v2.H43 gross profit USD',
                   358725.0,  pc.getRange('H43').getValue(), TOL_USD);

      // -- D5: PARITY vs legacy PROJECT_CARD -- REMOVE AT CUTOVER (Chunk 11) --
      // PC_v2 has a different row layout from legacy PC, so we can't do
      // cell-for-cell parity. We compare semantic values: the legacy total
      // (legacy C36) should match the v2 total (v2 C40) up to BESS adds
      // (legacy doesn't include BESS in its total -- this is one of the
      // bugs v2 fixes, so a strict equality will FAIL here, which is
      // EXPECTED and CORRECT).
      var legacyPc = ss.getSheetByName('PROJECT_CARD');
      if (legacyPc) {
        var legTotal = legacyPc.getRange('C36').getValue();
        var v2Total  = pc.getRange('C40').getValue();
        var v2Bess   = pc.getRange('C39').getValue();
        if (typeof legTotal === 'number' && typeof v2Total === 'number'
            && typeof v2Bess === 'number') {
          t.assertNear('PARITY PC USD (legacy total + BESS = v2 total)',
                       legTotal + v2Bess, v2Total, TOL_USD);
        } else {
          t.info('PC parity skipped',
                 'one of legacy.C36 / v2.C40 / v2.C39 is not a number');
        }
      } else {
        t.info('PROJECT_CARD parity skipped', 'legacy PC sheet not present');
      }
    }

    // ====================================================================
    // BLOCK E: CFE_OUTPUT_v2 -- annual savings deliverable
    // ====================================================================
    // CFE_OUTPUT_v2 layout (from setupCfeOutputTemplate / writeCfeOutputV2):
    //   Row 5-8   : header strip (tariff, service #, BESS strategy, etc.)
    //   Row 10    : KPI strip (3 formatted-string cells: Sin PV / Con PV /
    //               Con PV+BESS year-1 + year-2+)
    //   Row 12    : Section 1 title "1.  RECIBO CON PV"
    //   Row 13    : Ene..Dic month header
    //   Row 14-20 : Section 1 data (consumption, solar, exports, demand,
    //               billing, total, savings)
    //   Row 22    : Section 2 title "2.  RECIBO CON PV + BESS"
    //   Row 23    : Ene..Dic month header
    //   Row 24-31 : Section 2 data (Dmax, shaving, BESS savings, final bill)
    //   Row 33-34 : Annual cascade summary
    //
    // We lock monthly column-sums (annuals) rather than individual months --
    // monthly numbers shift slightly with sim re-runs but annual totals are
    // stable and customer-visible.
    // ====================================================================
    t.suite('E. CFE_OUTPUT_v2 -- annual energy/cost numbers');

    if (!ss.getSheetByName('CFE_OUTPUT_v2')) {
      t.fail('required sheet missing', 'CFE_OUTPUT_v2');
    } else {
      var cfe = ss.getSheetByName('CFE_OUTPUT_v2');

      // -- E1: identity (tariff + service number) --
      t.assert('CFE_v2.C5 tariff code', 'GDMTH',
               String(cfe.getRange('C5').getValue() || '').trim());
      t.assertNear('CFE_v2.C6 service number',
                   414240911417, cfe.getRange('C6').getValue(), 0);
      t.assert('CFE_v2.C8 BESS strategy', 'PEAK_SHAVING',
               String(cfe.getRange('C8').getValue() || '').trim());

      // -- E2: KPI banner strings (row 10, formatted) --
      var kpiSinPV   = String(cfe.getRange('B10').getValue() || '');
      var kpiConPV   = String(cfe.getRange('G10').getValue() || '');
      var kpiConBess = String(cfe.getRange('L10').getValue() || '');
      // RELOCKED 2026-06-16 (engine v4.28.0): sin-PV now comes from the single
      // engine base (con-PV row 39 + engine savings row 41) = $12,838,765, which
      // matches CLIENT_FINANCIALS' expected sin-PV to the peso. The old
      // $13,089,307 was the divergent legacy row-41 formula value.
      t.assertContains('CFE_v2.B10 annual sin PV = $12,838,765',
                       kpiSinPV, '12,838,765');
      t.assertContains('CFE_v2.G10 annual con PV = $10,910,746',
                       kpiConPV, '10,910,746');
      t.assertContains('CFE_v2.L10 con PV+BESS year-1 = $10,110,616',
                       kpiConBess, '10,110,616');
      t.assertContains('CFE_v2.L10 con PV+BESS year-2+ = $7,404,638',
                       kpiConBess, '7,404,638');

      // -- E3: annual rollups (col-sums Ene..Dic = C..N for each row) --
      var sumRow = function (row) {
        var cols = ['C','D','E','F','G','H','I','J','K','L','M','N'];
        var s = 0;
        for (var i = 0; i < cols.length; i++) {
          var v = cfe.getRange(cols[i] + row).getValue();
          if (typeof v === 'number') s += v;
        }
        return s;
      };

      t.assertNear('CFE_v2 annual consumption (row 14 sum) ~ 4,475,443 kWh',
                   4475443, sumRow(14), TOL_KWH);
      t.assertNear('CFE_v2 annual solar generation (row 15 sum) ~ 1,321,367 kWh',
                   1321367, sumRow(15), TOL_KWH);
      t.assertNear('CFE_v2 annual bill with PV (row 19 sum) ~ $10,910,746',
                   10910746, sumRow(19), TOL_MXN_BIG);
      t.assertNear('CFE_v2 annual PV savings (row 20 sum) ~ $1,928,019',
                   1928019,  sumRow(20), TOL_MXN_BIG);
      t.assertNear('CFE_v2 annual BESS savings (row 30 sum) ~ $800,130',
                   800130,   sumRow(30), TOL_MXN_BIG);
      t.assertNear('CFE_v2 annual final bill with BESS (row 31 sum) ~ $10,110,616',
                   10110616, sumRow(31), TOL_MXN_BIG);

      // -- E4: section anchors (template structure, not data) --
      t.assertContains('CFE_v2.B12 section 1 header',
                       String(cfe.getRange('B12').getValue() || ''),
                       'RECIBO CON PV');
      t.assertContains('CFE_v2.B22 section 2 header',
                       String(cfe.getRange('B22').getValue() || ''),
                       'RECIBO CON PV + BESS');
      t.assert('CFE_v2.C13 first month label', 'Ene',
               String(cfe.getRange('C13').getValue() || '').trim());
      t.assert('CFE_v2.N13 last month label',  'Dic',
               String(cfe.getRange('N13').getValue() || '').trim());

      // -- E6: Chunk 5 Session 3 additive elements (Option 2) --------------
      // Section 2 monthly numbers stay on the formula sheet (rows 30/31
      // locked above are UNCHANGED). These assertions cover the NEW
      // hourly-sim-sourced blocks that were ADDED this session:
      //   - tier banner + disclaimer at row 4 (and row 21)
      //   - Conservative/Expected/Upside + demand breakdown below the sheet
      //
      // The disclaimer is the LOCKED non-guarantee invariant: PROPOSAL-tier
      // output MUST carry it. This regression assertion makes that
      // permanent at the customer-sheet level (the unit test asserts it at
      // the function level; this asserts it survived end-to-end rendering).
      var bannerTop = String(cfe.getRange('B4').getValue() || '');
      // Banner is PROPOSAL when the hourly sim ran; if the sim was blocked
      // it would be SCREENING. CULLIGAN has a full run, so expect PROPOSAL.
      var bannerIsProposal = bannerTop.indexOf('PROPUESTA') >= 0;
      var bannerIsScreening = bannerTop.indexOf('SCREENING') >= 0;
      t.assertTrue('CFE_v2.B4 tier banner present (PROPOSAL or SCREENING)',
                   bannerIsProposal || bannerIsScreening);
      if (bannerIsProposal) {
        t.assertContains('CFE_v2.B4 PROPOSAL banner: not-guaranteed disclaimer',
                         bannerTop, 'no garantizados');
        t.assertContains('CFE_v2.B4 PROPOSAL banner: 15-min interval requirement',
                         bannerTop, 'intervalos de 15 minutos');
      }
      t.info('CFE_v2 Chunk 5 tier',
             'banner row 4 = "' + bannerTop.substring(0, 60) + '..."');

      // Section 2 source provenance: Option 2 keeps it on the formula sheet
      // this session. (Session 4 flips to hourly-sim post-validation.)
      t.info('CFE_v2 Section 2 source',
             'Option 2: monthly numbers from BESS_SIMULATION formula sheet; ' +
             'hourly-sim source swap deferred to Session 4 (post 15-min validation).');

      // -- E5: PARITY vs legacy CFE_OUTPUT -- REMOVE AT CUTOVER (Chunk 11) --
      // Skipped intentionally: legacy CFE_OUTPUT row layout changed across
      // engine versions and a positional diff would be brittle. The annual
      // numbers locked above are the source-of-truth check.
      t.info('CFE parity skipped',
             'Annual rollups locked above; row-level parity not asserted ' +
             '(legacy layout drift). REMOVE this info at cutover.');
    }

    // ====================================================================
    // BLOCK F: RFQ_*_v2 -- structural locks (item list shape, not prices)
    // ====================================================================
    // RFQs are written by the "Generate RFQs v2" menu item, NOT by the engine
    // run. If they're missing here, it usually means the menu wasn't clicked
    // after the engine run -- skip with INFO rather than failing.
    //
    // What we lock: item count, first/last item identity, presence of
    // SUBTOTAL row. We do NOT lock prices because suppliers fill those.
    // ====================================================================
    t.suite('F. RFQ_*_v2 -- item-list structure');

    var rfqExpectations = [
      // [sheet, expectedItemCount, firstItemRow, firstItemQty,
      //  firstItemDescContains, subtotalRow, subtotalLabelContains]
      ['RFQ_PANELES_v2',    1, 11,  1350, 'LONGI',
       12, 'PANELES'],
      ['RFQ_INVERSORES_v2', 2, 11,     1, 'SUN2000-100KTL',
       13, 'INVERSORES'],
      ['RFQ_ESTRUCTURA_v2', 2, 11,  1350, 'S-5',
       13, 'ESTRUCTURA'],
      ['RFQ_ELECTRICO_v2', 24, 11, 12600, '10 AWG',
       35, 'ELECTRICO'],
      ['RFQ_MONITOREO_v2',  6, 11,     1, 'monitoreo',
       17, 'MONITOREO'],
      ['RFQ_BESS_v2',       2, 11,     9, 'HW_LUNA',
       13, 'BESS']
    ];

    for (var k = 0; k < rfqExpectations.length; k++) {
      var e = rfqExpectations[k];
      var rfqName = e[0];
      var expCount = e[1];
      var firstRow = e[2];
      var expFirstQty = e[3];
      var firstDescNeedle = e[4];
      var subRow = e[5];
      var subLabelNeedle = e[6];

      var sh = ss.getSheetByName(rfqName);
      if (!sh) {
        t.info('skipped ' + rfqName,
               'sheet not found -- run "Generate RFQs v2" from the ARGIA menu');
        continue;
      }

      // Identity -- project name in C5
      t.assertContains(rfqName + '.C5 project name carries CULLIGAN',
                       String(sh.getRange('C5').getValue() || ''),
                       'CULLIGAN');

      // First item: row + qty + description
      t.assertNear(rfqName + '.D' + firstRow + ' first item qty',
                   expFirstQty,
                   sh.getRange('D' + firstRow).getValue(),
                   0.5);
      t.assertContains(rfqName + '.B' + firstRow + ' first item description',
                       String(sh.getRange('B' + firstRow).getValue() || ''),
                       firstDescNeedle);

      // Item count -- count rows with a numeric value in col A between
      // firstRow and subtotalRow - 1
      var actualCount = 0;
      for (var rr = firstRow; rr < subRow; rr++) {
        var a = sh.getRange('A' + rr).getValue();
        if (typeof a === 'number') actualCount++;
      }
      t.assert(rfqName + ' item count', expCount, actualCount);

      // SUBTOTAL row present at expected row
      t.assertContains(rfqName + '.B' + subRow + ' SUBTOTAL row',
                       String(sh.getRange('B' + subRow).getValue() || ''),
                       'SUBTOTAL');
      t.assertContains(rfqName + '.B' + subRow + ' SUBTOTAL category match',
                       String(sh.getRange('B' + subRow).getValue() || ''),
                       subLabelNeedle);
    }

    // ====================================================================
    // BLOCK G: engine version stamp
    // ====================================================================
    t.suite('G. _META engine version');

    var meta = ss.getSheetByName('_META');
    if (meta) {
      var engineVer = String(meta.getRange('B4').getValue() || '');
      // Relocked at 4.0.0 (2026-05-28). The 4.0.0 BESS dispatch rewrite
      // changed CFE *savings/economics* numbers, but this baseline pins only
      // physical/material values (BESS capacity, power, topology, strategy
      // LABEL, BOM material subtotals) and PV/structural calcs — none of
      // which the dispatch change touches. So the pinned numbers above carry
      // forward unchanged; only the version stamp is bumped.
      if (engineVer !== '4.12.1') {
        t.info('engine version drift',
          'v2 baseline relocked at engine v4.0.0 (2026-05-28). ' +
          'Current engine v' + engineVer + '. If the asserts above pass, ' +
          'the baseline carries forward cleanly. If they fail, audit which ' +
          'numbers changed and re-lock with an explicit CHANGELOG entry.');
      } else {
        t.assert('engine version matches v2 baseline', '4.12.1', engineVer);
      }
    } else {
      t.info('engine version unknown', '_META sheet not present');
    }
  }
});
